var JScountries = {
	"AE":"Utd.Arab Emir.",
	"AL":"Albania",
	"AM":"Armenia",
	"AO":"Angola",
	"AR":"Argentina",
	"AT":"Austria",
	"AU":"Australia",
	"AZ":"Azerbaijan",
	"BA":"Bosnia and Herzegovina",
	"BB":"Barbados",
	"BD":"Bangladesh",
	"BE":"Belgium",
	"BG":"Bulgaria",
	"BH":"Bahrain",
	"BR":"Brazil",
	"BS":"Bahamas",
	"BY":"Belarus",
	"CA":"Canada",
	"CH":"Switzerland",
	"CI":"Ivory Coast",
	"CL":"Chile",
	"CN":"China",
	"CO":"Colombia",
	"CR":"Costa Rica",
	"CZ":"Czech Republic",
	"DE":"Germany",
	"DK":"Denmark",
	"DO":"Dominican Republic",
	"DZ":"Algeria",
	"EC":"Ecuador",
	"EE":"Estonia",
	"EG":"Egypt",
	"ES":"Spain",
	"FI":"Finland",
	"FR":"France",
	"GB":"United Kingdom",
	"GE":"Georgia",
	"GH":"Ghana",
	"GR":"Greece",
	"GT":"Guatemala",
	"HN":"Honduras",
	"HR":"Croatia",
	"HU":"Hungary",
	"ID":"Indonesia",
	"IE":"Ireland",
	"IN":"India",
	"IQ":"Iraq",
	"IR":"Iran",
	"IT":"Italy",
	"JM":"Jamaica",
	"JO":"Jordan",
	"JP":"Japan",
	"KE":"Kenya",
	"KG":"Kyrgistan",
	"KR":"South Korea",
	"KW":"Kuwait",
	"KZ":"Kazakhstan",
	"LB":"Lebanon",
	"LT":"Lithuania",
	"LU":"Luxembourg",
	"LV":"Latvia",
	"MA":"Morocco",
	"MD":"Moldova",
	"MK":"Macedonia",
	"MM":"Burma",
	"MX":"Mexico",
	"MY":"Malaysia",
	"NG":"Nigeria",
	"NI":"Nicaragua",
	"NL":"Netherlands",
	"NO":"Norway",
	"NZ":"New Zealand",
	"OM":"Oman",
	"PA":"Panama",
	"PE":"Peru",
	"PH":"Philippines",
	"PK":"Pakistan",
	"PL":"Poland",
	"PS":"Palestine",
	"PT":"Portugal",
	"QA":"Qatar",
	"RO":"Romania",
	"RS":"Serbia",
	"RU":"Russian Fed.",
	"SA":"Saudi Arabia",
	"SE":"Sweden",
	"SG":"Singapore",
	"SI":"Slovenia",
	"SK":"Slovakia",
	"SN":"Senegal",
	"SV":"El Salvador",
	"SY":"Syria",
	"TH":"Thailand",
	"TJ":"Tajikistan",
	"TM":"Turkmenistan",
	"TN":"Tunisia",
	"TR":"Turkey",
	"TT":"Trinidad and Tobago",
	"TW":"Taiwan",
	"UA":"Ukraine",
	"US":"USA",
	"UZ":"Uzbekistan",
	"VE":"Venezuela",
	"YE":"Yemen",
	"ZA":"South Africa",
	"ZM":"Zambia",
	"ZW":"Zimbabwe",
};


var JSdivisions = {
	"AH":"Animal Health",
	"Alcon":"Alcon",
	"Corporate":"Corporate",
	"NB":"NBS",
	"NCH":"Consumer Health",
	"NIBR":"Novartis Institutes for BioMedical Research (NIBR)",
	"NVD":"Vaccines & Diagnostics",
	"OTC":"Over The Counter",
	"Pharma":"Pharma",
	"Sandoz":"Sandoz",
};


var JStherapeuticareas = {
	"Arthritis_bone":"Arthritis and bone",
	"Cardiovascular_Metabolism":"Cardiovascular and Metabolism",
	"Infectious_diseases":"Infectious diseases",
	"Neuroscience":"Neuroscience",
	"Oncology":"Oncology",
	"Ophthalmics":"Ophthalmics",
	"Respiratory":"Respiratory",
	"Transplantation":"Transplantation"
};


var JSfunctions = {
	"BS":"BD&L & Strategic Planning",
	"ComGenMana":"Commercial & General Management",
	"CorporateAffairs":"Communications  & Public Affairs",
	"CorporateStrategy":"Corporate Strategy",
	"DevelopmentMedical":"Development & Medical",
	"FacilitiesAdministration":"Facilities and Administration",
	"Finance":"Audit & Finance",
	"HumanResources":"Human Resources",
	"InformationTechnology":"Information Technology",
	"Legal_IntellectualProperty":"Legal & Intellectual Property & Compliance",
	"Logistics":"Logistics",
	"MA":"Market Access",
	"Marketing":"Marketing",
	"Procurement":"Procurement",
	"Production":"Production",
	"QA":"Quality",
	"RD":"Research & Development",
	"Research":"Research",
	"Sales":"Sales",
	"TO":"Technical Operations",
};
